
export const agentTools = [
  { id: "1", name: "add_new_task" },
  { id: "2", name: "build_review_merge_request_context" },
  { id: "3", name: "ci_linter" },
  { id: "4", name: "confirm_vulnerability" },
  { id: "5", name: "create_commit" },
  { id: "6", name: "create_epic" },
  { id: "7", name: "create_issue" },
  { id: "8", name: "create_issue_note" },
  { id: "9", name: "create_merge_request" },
  { id: "10", name: "create_merge_request_note" },
  { id: "11", name: "create_plan" },
  { id: "12", name: "create_vulnerability_issue" },
  { id: "13", name: "create_work_item" },
  { id: "14", name: "create_work_item_note" },
  { id: "15", name: "dismiss_vulnerability" },
  { id: "16", name: "extract_lines_from_text" },
  { id: "17", name: "get_commit" },
  { id: "18", name: "get_commit_comments" },
  { id: "19", name: "get_commit_diff" },
  { id: "20", name: "get_current_user" },
  { id: "21", name: "get_epic" },
  { id: "22", name: "get_epic_note" },
  { id: "23", name: "get_issue" },
  { id: "24", name: "get_issue_note" },
  { id: "25", name: "get_job_logs" },
  { id: "26", name: "get_merge_request" },
  { id: "27", name: "get_pipeline_errors" },
  { id: "28", name: "get_pipeline_failing_jobs" },
  { id: "29", name: "get_plan" },
  { id: "30", name: "get_previous_session_context" },
  { id: "31", name: "get_project" },
  { id: "32", name: "get_repository_file" },
  { id: "33", name: "get_security_finding_details" },
  { id: "34", name: "get_vulnerability_details" },
  { id: "35", name: "get_wiki_page" },
  { id: "36", name: "get_work_item" },
  { id: "37", name: "get_work_item_notes" },
  { id: "38", name: "gitlab_api_get" },
  { id: "39", name: "gitlab_blob_search" },
  { id: "40", name: "gitlab_commit_search" },
  { id: "41", name: "gitlab_documentation_search" },
  { id: "42", name: "gitlab_graphql" },
  { id: "43", name: "gitlab_group_project_search" },
  { id: "44", name: "gitlab_issue_search" },
  { id: "45", name: "gitlab_merge_request_search" },
  { id: "46", name: "gitlab_milestone_search" },
  { id: "47", name: "gitlab_note_search" },
  { id: "48", name: "gitlab_user_search" },
  { id: "49", name: "gitlab_wiki_blob_search" },
  { id: "50", name: "link_vulnerability_to_issue" },
  { id: "51", name: "link_vulnerability_to_merge_request" },
  { id: "52", name: "list_all_merge_request_notes" },
  { id: "53", name: "list_commits" },
  { id: "54", name: "list_epic_notes" },
  { id: "55", name: "list_epics" },
  { id: "56", name: "list_group_audit_events" },
  { id: "57", name: "list_instance_audit_events" },
  { id: "58", name: "list_issue_notes" },
  { id: "59", name: "list_issues" },
  { id: "60", name: "list_merge_request_diffs" },
  { id: "61", name: "list_project_audit_events" },
  { id: "62", name: "list_repository_tree" },
  { id: "63", name: "list_security_findings" },
  { id: "64", name: "list_vulnerabilities" },
  { id: "65", name: "list_work_items" },
  { id: "66", name: "post_duo_code_review" },
  { id: "67", name: "post_sast_fp_analysis_to_gitlab" },
  { id: "68", name: "remove_task" },
  { id: "69", name: "revert_to_detected_vulnerability" },
  { id: "70", name: "run_glql_query" },
  { id: "71", name: "run_tests" },
  { id: "72", name: "set_task_status" },
  { id: "73", name: "update_epic" },
  { id: "74", name: "update_issue" },
  { id: "75", name: "update_merge_request" },
  { id: "76", name: "update_task_description" },
  { id: "77", name: "update_vulnerability_severity" },
  { id: "78", name: "update_work_item" },
  // IDE only
  { id: "79", name: "create_file_with_contents" },
  { id: "80", name: "edit_file" },
  { id: "81", name: "find_files" },
  { id: "82", name: "grep" },
  { id: "83", name: "list_dir" },
  { id: "84", name: "mkdir" },
  { id: "85", name: "read_file" },
  { id: "86", name: "read_files" },
  { id: "87", name: "run_command" },
  { id: "88", name: "run_git_command" },
];

export const agentUILogEvent = [
    {id: "1", name: "on_agent_final_answer"},
    {id: "2", name: "on_tool_execution_success"},
    {id: "3", name: "on_tool_execution_failed"},
]

export const oneOffUILogEvent = [
    {id: "1", name: "on_tool_call_input"},
    {id: "2", name: "on_tool_execution_success"},
    {id: "3", name: "on_tool_execution_failed"},
]